.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. hopium_qt test_hopium_qt
clean: FORCE
	$(MAKE) -C .. hopium_qt_clean test_hopium_qt_clean
check: FORCE
	$(MAKE) -C .. test_hopium_qt_check
hopium-qt hopium-qt.exe: FORCE
	 $(MAKE) -C .. hopium_qt
