#!/usr/bin/env bash
#
#  hopiumd The Hopium server.
#
#
# chkconfig: 345 80 20
# description: hopiumd
# processname: hopiumd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/hopiumd, see below
if [ -f /etc/sysconfig/hopiumd ]; then
        . /etc/sysconfig/hopiumd
fi

RETVAL=0

prog=hopiumd
# you can override the lockfile via BLACKMORED_LOCKFILE in /etc/sysconfig/hopiumd
lockfile=${BLACKMORED_LOCKFILE-/var/lock/subsys/hopiumd}

# hopiumd defaults to /usr/bin/hopiumd, override with BLACKMORED_BIN
hopiumd=${BLACKMORED_BIN-/usr/bin/hopiumd}

# hopiumd opts default to -disablewallet, override with BLACKMORED_OPTS
hopiumd_opts=${BLACKMORED_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $bitcoind $bitcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
